# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d21af8fa68edbb88e2b4e7a379926a5144811d67e021be4ca79c59e92c978eee0ce34ce48de8703a12bced1685cab4080261e497566d13034bf84881eee62148

test:
  secret_key_base: 6bef077a610c8ed6c75f8604fb40b85387ee318b325abdfb27dd60dae1ef583d1886b7e9e454629b59ae85ded4759b391e66972e0e91684462a9a757a44566a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
